version: "3"
services:
  bff-zeus-dev:
    build:
      context: ./bff/zeus
      dockerfile: Dockerfile.dev
    image: zeus-dev
    ports:
      - 3000:3000
    volumes:
      - ./bff/zeus/src:/app/src
