SHELL := /bin/bash

preview:
	pulumi preview
setup:
	source ~/.nvm/nvm.sh && nvm use && npm install
pulumi-stack-ls:
	pulumi stack ls
pulumi-select-dev:
	pulumi stack select dev
pulumi-select-stg:
	pulumi stack select stg
pulumi-select-prd:
	pulumi stack select prd
